feat: Added hw02, unpack fanction
dmitrii-a/hw_go pull request #2
Opened 2023-10-01 18:31 UTC by dmitrii-a

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-10-02 05:14 UTC, vladislavmass requested changes
Хорошее начало. Решение проходит все тесты с кодировкой ASCII, но не работает для многобайтовых символов. Для демонстрации проблемы можно использовать следующий тест-кейс `{input: "aabг2", expected: "aabгг"},`

2023-10-02 05:14 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(data); i++ {
В go нельзя таким образом итерироваться по рандомный строкам, так как итерация идет не по символам а по их первому байту. И когда делается операция data[i] получается не сам символ а лишь его первый байт.

2023-10-02 22:07 UTC, dmitrii-a commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(data); i++ {
Спасибо, не учёл, что символы могут быть разные

2023-10-03 19:24 UTC, vladislavmass requested changes
Хорошее начало. Теперь решение без проблем работает с многобайтовый кодировкой. И в принципе базовое решение можно принять на 8 балов, -2 за работу со строками вместо рун, но расширение решение не проходит тест вида. `aa\` Эта строка должна приводить к ошибки, так как последний слэш ничего не экранирует

2023-10-03 19:24 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	data := []rune(s)
Данная нотация приведет к выделению памяти и копированию строки. Это не очень оптимально по памяти и в данном случае очень легко исправляется. Просто надо заменить цикл фор на фор рандж

2023-10-03 19:24 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		currValue := string(data[i])
Нет никакого смысла оперировать строкой, лучше работать с рунами

2023-10-07 19:40 UTC, vladislavmass approved these changes
Отличная работа. Принято

2023-10-07 19:44 UTC, merged