feat: Added hw05
dmitrii-a/hw_go pull request #6
Opened 2023-11-07 15:05 UTC by dmitrii-a

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-11-09 19:04 UTC, vladislavmass requested changes
Хорошее начало, но есть потенциальная паника. А также код вышел очень сложный, так как в одной структуре находятся сразу 3 примитива синхронизации

2023-11-09 19:04 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +			if err := task(); err != nil {
Неучтен вариант того, что task==nil и тогда nil() приведет к панике.

2023-11-19 07:13 UTC, vladislavmass requested changes
Работа стала  намного лучше но при выходе из кода канал taskCh не закрывается и это является серьезной ошибкой. Также рекомендую обдумать вариант с избавлением от канала stop и о прекращение работы воркеров через закрытие канала taskCh( для этого у нас есть for по каналу)

2023-11-19 07:13 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +			wg.Done()
Обычно wg.Done вещают на канал, а не на задание.

2023-11-19 07:13 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +		tasksCh <- task
TaskCh не закрыт.

2023-11-19 11:49 UTC, dmitrii-a commented on hw05_parallel_execution/run.go
> +		tasksCh <- task
По этому поводу отписался в сообщениях, т.к. не согласен с этим

2023-11-19 11:55 UTC, dmitrii-a commented on hw05_parallel_execution/run.go
> +			wg.Done()
Я решил сделать таким образом, т.к. более явно происходит контроль по моему мнению, когда каждая задача взятая в работу будет обработана и подсчитана корректно, а если задач нет, то и wg не работает. Но конечно можно сделать и так.
`
func worker(tasks chan Task, errorCounter *int64, maxErrorsCount int64, wg *sync.WaitGroup) {
	defer wg.Done()
	for task := range tasks {
		if atomic.LoadInt64(errorCounter) < maxErrorsCount && task != nil {
			if err := task(); err != nil {
				atomic.AddInt64(errorCounter, 1)
			}
		}
	}
}

func Run(tasks []Task, n, m int) error {
	if n == 0 {
		return ErrNoWorkers
	}
	var (
		errorCounter   = int64(0)
		maxErrorsCount = int64(m)
		tasksCh        = make(chan Task, m)
		wg             = &sync.WaitGroup{}
	)
	for i := 0; i < n; i++ {
		wg.Add(1)
		go worker(tasksCh, &errorCounter, maxErrorsCount, wg)
	}
	for _, task := range tasks {
		if atomic.LoadInt64(&errorCounter) >= maxErrorsCount {
			break
		}
		tasksCh <- task
	}
	close(tasksCh)
	wg.Wait()
	if errorCounter >= maxErrorsCount {
		return ErrErrorsLimitExceeded
	}
	return nil
}
`

2023-11-20 19:07 UTC, vladislavmass approved these changes

2023-12-07 21:16 UTC, merged